### PR TITLE
1 distributed web infrastructure

### PR DESCRIPTION
**Pull request by Shikadia**

### CODE REVIEW

**Comment by Shikadia** [comment]
I previously used lucid chart, but i had to change it as only signed user can view the design.

**Review by JayJay247in — COMMENTED** [review]
The image picture isn't clear sir.... Its not totally visible and readable..... The one in lucid was more palatable than the imgur one....
Screenshot_20231124-180724_Chrome
Screenshot_20231124-180526_Chrome
These are the screen shots of the two image files..... Please rectify that for readability....

**Comment by Shikadia** [comment]
on my end, It just ok using imgur

image

**Comment by Shikadia** [comment]
can't we just manage it ? as it will entail me to start again, using something else?

**Review by kenrique100 — APPROVED** [review]
Very Good

**Comment by JayJay247in** [comment]
Kenrique I haven't still, seen your work..... The 1st deadline for manual review is down....

**Comment by kenrique100** [comment]
am done u can check
just did all in one since they were no repo security of who can control the
main i just commit pull and merged

**Pull request merged**
